# Generated by Django 5.2.10 on 2026-01-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='web_user',
            new_name='users',
        ),
    ]
